/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c FMRadioAdaptor -a fmradioadaptor fmradio-backend.xml com.akozhan.fmradio
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "fmradioadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class FMRadioAdaptor
 */

FMRadioAdaptor::FMRadioAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

FMRadioAdaptor::~FMRadioAdaptor()
{
    // destructor
}

void FMRadioAdaptor::exit()
{
    // handle method call com.akozhan.fmradio.exit
    QMetaObject::invokeMethod(parent(), "exit");
}

void FMRadioAdaptor::scan(bool forward)
{
    // handle method call com.akozhan.fmradio.scan
    QMetaObject::invokeMethod(parent(), "scan", Q_ARG(bool, forward));
}

void FMRadioAdaptor::start()
{
    // handle method call com.akozhan.fmradio.start
    QMetaObject::invokeMethod(parent(), "start");
}

void FMRadioAdaptor::stop()
{
    // handle method call com.akozhan.fmradio.stop
    QMetaObject::invokeMethod(parent(), "stop");
}

void FMRadioAdaptor::tuneToFreq(double freq)
{
    // handle method call com.akozhan.fmradio.tuneToFreq
    QMetaObject::invokeMethod(parent(), "tuneToFreq", Q_ARG(double, freq));
}

