/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c FMRadioAdaptor -a fmradioadaptor fmradio-backend.xml com.akozhan.fmradio
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef FMRADIOADAPTOR_H_1328611730
#define FMRADIOADAPTOR_H_1328611730

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.akozhan.fmradio
 */
class FMRadioAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.akozhan.fmradio")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.akozhan.fmradio\">\n"
"    <method name=\"tuneToFreq\">\n"
"      <arg direction=\"in\" type=\"d\" name=\"freq\"/>\n"
"    </method>\n"
"    <method name=\"scan\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"forward\"/>\n"
"    </method>\n"
"    <method name=\"start\"/>\n"
"    <method name=\"stop\"/>\n"
"    <method name=\"exit\"/>\n"
"    <signal name=\"tuned\">\n"
"      <arg type=\"d\" name=\"freq\"/>\n"
"      <arg type=\"u\" name=\"signal\"/>\n"
"    </signal>\n"
"    <signal name=\"signalChanged\">\n"
"      <arg type=\"u\" name=\"signal\"/>\n"
"      <arg type=\"b\" name=\"stereo\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    FMRadioAdaptor(QObject *parent);
    virtual ~FMRadioAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void exit();
    void scan(bool forward);
    void start();
    void stop();
    void tuneToFreq(double freq);
Q_SIGNALS: // SIGNALS
    void signalChanged(uint signal, bool stereo);
    void tuned(double freq, uint signal);
};

#endif
